### ISSUE TITLE
Artifacts Summary / test

()

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/hl7-be-fhir-medication#44]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|---|---|
| Artifacts Summary | test

 | test riziv |  | HL7.BE.FHIR.MEDICATIONIG\Artifacts Summary - FHIR v4.0.1 |

**Comment by JensPenny** [comment]
No actual task
