### ISSUE TITLE
Resource Profile: BeMedicationDispense / regord - record()

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/hl7-be-fhir-medication#47]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| Resource Profile: BeMedicationDispense | regord - record | JCT |  | HL7.BE.FHIR.MEDICATIONIG\Profile - Medication Dispense - FHIR v4.0.1 |

**Comment by JensPenny** [comment]
Merged & fixed
