### ISSUE TITLE
Medication Dispense / test(test@test.com)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/hl7-be-fhir-medication#68]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| Medication Dispense | test | test | test@test.com | HL7.BE.FHIR.MEDICATIONIG\Artifacts Summary - FHIR v4.0.1 |

**Comment by JensPenny** [comment]
Closed due to not having a real task attached to it
